import Footer from '@/Components/Shared/Footer';
import api from '@/api/api';
import Doctors from '../details/Components/Doctors';



export const metadata = {
  title: "All AppointMents -- DocAppoint",
  description: "Generated by create next app",
};

const AppointMentsPage = async () => {

    let doctors = [];

    try {
        const response = await api.get('/doctors');

        doctors = response?.data?.payload;

    } catch (error) {
        console.log(error?.response?.data?.message);
    }

    return (
        <div>

            <div className='mt-16 w-11/12 py-12 max-w-7xl mx-auto'>

                <div className='text-center'>

                    <h2 className='text-3xl md:text-4xl font-bold'>
                        All Appointments
                    </h2>

                    <p className='text-muted mt-2'>
                        Built around your health and your time
                    </p>

                </div>

                <Doctors doctors={doctors} />

            </div>

            <Footer />

        </div>
    );
};

export default AppointMentsPage;