import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Shared/Navbar";
import ToastProvider from "@/Components/Shared/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DocAppoint -- Book Trusted Doctors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      data-theme='light'
    >
      <body className="min-h-full flex flex-col">
          <Header />
          {children}
          <ToastProvider />
      </body>
    </html>
  );
}
