import Footer from "@/Components/Shared/Footer";
import Toggle from "./Components/Toggle";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";


export const metadata = {
  title: "Dashboard -- DocAppoint",
  description: "Generated by create next app",
};



const DashboardPage =async () => {
    const {token} = await auth.api.getToken({
        headers: await headers(),
    });
    

    console.log(token);

    return (
        <div className=''>
            <div className='mt-16 px-4 py-12 max-w-7xl mx-auto'>
                <div className=''>
                    <h2 className='text-3xl md:text-4xl font-bold'>Dashboard</h2>
                </div>
                <Toggle token={token} />

            </div>
            <Footer />
        </div>
    );
};

export default DashboardPage;