import Footer from "@/Components/Shared/Footer";
import Toggle from "./Components/Toggle";


export const metadata = {
  title: "All Appointments -- DocAppoint",
  description: "Generated by create next app",
};



const DashboardPage = () => {
    

    return (
        <div className=' max-w-7xl mx-auto'>
            <div className='mt-16 px-4 py-12'>
                <div className=''>
                    <h2 className='text-3xl md:text-4xl font-bold'>Dashboard</h2>
                </div>
                <Toggle />

            </div>
            <Footer />
        </div>
    );
};

export default DashboardPage;